name: master

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run gen-api
      - run: npm run build
        env:
          NODE_ENV: production
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: ./dist
  deploy-staging:
    name: Deploy staging
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v1
        with:
          private-key: ${{ secrets.STAGING_SSH_KEY }}
          public-key: ${{ secrets.STAGING_SSH_KEY_PUBLIC }}
          known-hosts: ${{ secrets.STAGING_KNOWN_HOSTS }}
      - uses: actions/download-artifact@v1
        with:
          name: dist
          path: ./dist
      - name: Deploy
        run: rsync -e ssh --rsync-path='sudo rsync' -rltpzhv --delete ./dist ${{ secrets.STAGING_DEPLOY_USER }}@${{ secrets.STAGING_DEPLOY_HOST }}:${{ secrets.STAGING_DEPLOY_RSYNC_DESTINATION }}
